### ISSUE TITLE
Hack Smart Charger

### ISSUE THREAD

**Issue by Marnonel6** [Marnonel6/ROS2_offboard_drone_control#74]

**Comment by Marnonel6** [comment]
If Lipo charger is set in correct Lipo setting the charge can now be automatically triggered by a MCU.

## TASKS:

- [ ] Create adapter from LIPO charger to LIPO battery
- [ ] Create 3s to 6s cell connection wires
- [ ] Integrate to docking station
- [ ] Auto detect drone
- [ ] Switch on charging
- [ ] Stop charging when battery is full
